name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the iphonemax-publish-to-gcr Docker image
        run: |
          echo $GHCR_PAT | docker login ghcr.io -u isajidh --password-stdin
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        docker build . --tag ghcr.io/isajidh/iphonemax-publish-to-gcr:latest
        docker run ghcr.io/isajidh/iphonemax-publish-to-gcr:latest
        docker push ghcr.io/isajidh/iphonemax-publish-to-gcr:latest