name: Push to Docker Hub then to GHCR
on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1 Checkout access to git repo
        uses: actions/checkout@v3

      - name: 2 Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 3 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 4 Build and push to Docker repository
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/iphonemaxcitest:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/iphonemaxcitest:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/iphonemaxcitest:buildcache,mode=max

      - name: 5 Push to GitHub Container Registry
        uses: actions/checkout@v3
      - name: Build the iphonemax-publish-to-gcr Docker image
        run: |
          echo $GHCR_PAT | docker login ghcr.io -u isajidh --password-stdin
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        docker build . --tag ghcr.io/isajidh/iphonemax-publish-to-gcr:latest
        docker run ghcr.io/isajidh/iphonemax-publish-to-gcr:latest
        docker push ghcr.io/isajidh/iphonemax-publish-to-gcr:latest
