name: publish to  github container registry
on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1 Checkout access to github repo
      - uses: actions/checkout@v2

      - name: 2 Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3 Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/isajidh/iphonemax-publish-to-gcr:latest
          docker run ghcr.io/isajidh/iphonemax-publish-to-gcr:latest
          docker push ghcr.io/isajidh/iphonemax-publish-to-gcr:latest
